### ISSUE TITLE
Support for Vaadin 14

### ISSUE THREAD

**Issue by Samushel** [vaadin-component-factory/password-strength#1]
After upgrading to Vaadin 14, this plugin no longer works because it is looking for a template in the bower_components folder. 

https://github.com/vaadin-component-factory/password-strength/blob/master/password-strength/src/main/java/com/vaadin/componentfactory/PasswordStrength.java#L32

```
java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'vcf-password-strength' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:136) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-2.0.8.jar:2.0.8]
	at com.vaadin.componentfactory.PasswordStrength.<init>(PasswordStrength.java:33) ~[password-strength-1.1.0.jar:1.1.0]
```

**Comment by samulivaadin** [comment]
Added npm support into addon version 2.0.0. Older 1.1.0 works with V14 compatibility (bower) mode.
